const GET_BOOKS = 'GET_BOOKS';
const ADD_BOOK = 'ADD_BOOK';
const EDIT_BOOK = 'EDIT_BOOK';
const DELETE_BOOK ='DELETE_BOOK';
const EDIT_BOOK_FIELD = 'EDIT_BOOK_FIELD';

export default{
    GET_BOOKS,
    ADD_BOOK,
    EDIT_BOOK,
    EDIT_BOOK_FIELD,
    DELETE_BOOK
}

